Sample refactor
zalaby12/amazing-me pull request #47
Opened 2017-09-06 23:14 UTC by zalaby12

@southgatew @masteryoda123  @DKim0509  @VernBuck pull this and make sure you can run it. 

if we are good to go, then confirm the review if you're ok with it. otherwise, say so!

2017-09-06 23:22 UTC, southgatew requested changes
There were still a few files that git was tracking. Use [this](https://www.gitignore.io/api/linux%2Cmacos%2Cwindows%2Candroidstudio) to generate a gitignore that should include everything. Otherwise the app runs fine

2017-09-06 23:41 UTC, southgatew approved these changes

2017-09-07 00:27 UTC, masteryoda123 approved these changes

2017-09-07 00:31 UTC, VernBuck approved these changes
Good to go!

2017-09-07 00:31 UTC, DKim0509 approved these changes
works for me

2017-09-07 00:35 UTC, merged